"""Internal message types and engine events.

This module defines the core data structures that flow through archie:

1. ContentBlocks — the building blocks of conversation turns. A single turn
   (user or assistant message) can contain multiple blocks. For example, an
   assistant response might be [TextBlock, ToolUseBlock, ToolUseBlock] when
   the model generates text and then calls two tools.

2. EngineEvents — what the Engine yields to the UI as it processes a turn.
   The UI subscribes to these to update the display in real-time.

These types are PROVIDER-AGNOSTIC — they don't know about Bedrock's wire format.
The LLM client (llm/bedrock.py) translates between these and the provider's format.
"""

from dataclasses import dataclass

# --- Content Blocks ---
# These represent the content of a single message/turn in the conversation.
# A turn's content is a list[ContentBlock].


@dataclass
class TextBlock:
    """A block of text content (the most common type).

    In a user message: what the user typed.
    In an assistant message: what the model generated.
    """

    text: str


@dataclass
class ToolUseBlock:
    """The model wants to call a tool.

    Generated by the model (appears in assistant messages).
    The tool_use_id is generated by the provider (Bedrock) and must be
    propagated to the corresponding ToolResultBlock so the model can
    match results to requests.
    """

    tool_use_id: str
    name: str
    input: dict


@dataclass
class ToolResultBlock:
    """The result of executing a tool.

    Generated by the Engine after running a tool handler.
    Appears in a separate "user" turn (that's how Bedrock's protocol works —
    tool results are sent as user messages with toolResult content blocks).
    """

    tool_use_id: str
    content: str
    is_error: bool = False


# Union type for all content blocks.
type ContentBlock = TextBlock | ToolUseBlock | ToolResultBlock


# --- Engine Events ---
# These are yielded by the Engine as it processes a user message.
# The UI consumes these to update the display in real-time.


@dataclass
class TextDelta:
    """A chunk of generated text arrived. Append to the streaming display."""

    text: str


@dataclass
class ToolCallStart:
    """The model is about to call a tool. Show the tool name and args in the UI."""

    tool_use_id: str
    name: str
    input: dict


@dataclass
class ToolCallResult:
    """A tool finished executing. Show the result in the UI."""

    tool_use_id: str
    name: str
    content: str
    is_error: bool


@dataclass
class TurnComplete:
    """The engine finished processing this user message.

    This is the final event for a given engine.run() call.
    Token counts are summed across all LLM calls in this turn
    (if tools caused multiple round-trips to the model).
    """

    input_tokens: int
    output_tokens: int
    stop_reason: str


# Union type for all engine events.
type EngineEvent = TextDelta | ToolCallStart | ToolCallResult | TurnComplete
